#! /bin/sh
#
# LVDrestart	This script will stop agsd and reboot the system.  After stopping
#               the daemon, it will look for new version of the daemon first.
#               If found, copy current version to backup directory, unzip new
#               ags.gz file, mv unzipped agsd file to standard directory, then
#               reboot.
#
# Version:	1.0
#
start-stop-daemon -K -q -p /var/run/agsd.pid
if [ -e "/laservision/sbin/ags.gz" ]; then
    su
    gunzip /laservision/sbin/ags.gz
    cp /laservision/sbin/agsd /laservision/sbin/agsd.orig
    mv /laservision/sbin/ags /laservision/sbin/agsd
    chmod 777 /laservision/sbin/agsd
fi
umount -a
sync
echo b > /proc/sysrq-trigger
# Should never get to exit!
exit $?
